(in-package #:a21.day-1)

(defun prompt (part)
  (utils:echo-prompt 1 part))

(defun part-1 ()
  (let ((input (utils:read-file-lines "inputs/day1-1.txt" 'integer))
        (count 0)
        (prev nil))
    (dolist (num input)
      (when (and prev (> num prev))
        (incf count))
      (setf prev num))
    count))

(defun part-2 ()
  (do* ((input (utils:read-file-lines "inputs/day1-1.txt" 'integer) (cdr input))
        (count 0)
        (window (list (first input)
                      (second input)
                      (third input))
                (list (first input)
                      (second input)
                      (third input)))
        (prev nil sum)
        (sum (utils:sum window) (utils:sum window)))
       ((null input) count)
    (when (and prev (> sum prev))
      (incf count))))
